name: Fetch and Push Lotto Results

on:
  schedule:
    - cron: '0 22 * * *'  # Every day at 10 PM UTC (~11 PM UK time)
  workflow_dispatch:      # Optional: lets you run it manually

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run fetch script
        run: python fetch_lotto_results.py

      - name: Commit and push if changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add lotto_results.lot
          git diff --cached --quiet || git commit -m "🔄 Auto-update lotto_results.lot"
          git push
