name: Fetch and Push EuroMillions Results

on:
  schedule:
    - cron: '30 22 * * *'     # Daily, 22:30 UTC (adjust if you like)
  workflow_dispatch:

permissions:
  contents: write             # allow push back to repo

jobs:
  update-euromillions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run fetch script
        run: python fetch_euromillions_results.py

      - name: Commit & push if file changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add euromillions_results.lot
          git diff --cached --quiet || git commit -m "🔄 Auto-update euromillions_results.lot"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
